### ISSUE TITLE
#amigarus

### ISSUE THREAD

**Issue by devstratum** [OlegMishin/A1200_8MB_FASTRAM#1]
Привет Олег! Если есть телега, то народ хотел бы с тобой пообщаться в группе русских амижников #amigarus

**Comment by OlegMishin** [comment]
Привет Сергей,
К сожалению, телеги у меня нет. Есть другие варианты(форум, whatsapp etc)?

Олег

**Comment by devstratum** [comment]
Принято, если будет telegram, заходи в русскоязычную группу амижников.
Тебе от народа привет и уважуха за открытые проекты железа для платформ компьютеров Amiga!

**Comment by OlegMishin** [comment]
Большое спасибо! Буду иметь в виду :)
