### ISSUE TITLE
Amiga wont boot with card in it, need help

### ISSUE THREAD

**Issue by Retrofletch** [OlegMishin/A1200_8MB_FASTRAM#2]
I am using EPM7128STC100-10 and im programming it with the pld_ram.pof file found in output files, it programs and verifies fine, but card will not boot or even output video with card in.

I have jumper on
no battery or RTC installed to simplify things.
I have tried to boot a card with no ram chips installed at all and still no boot or video output, the machine just dont want to start.
Im not sure that i programmed it with correct file but it atleast seems like it? and chips should be correct because pof file states "EPM7128STC100-10" in the header.

soldering is good, ive double tripple checked.

any ideas? should card boot with no ram chips or not?

rev1 pcb

**Comment by OlegMishin** [comment]
Hi, 
In general, I would start troubleshooting from the main connector. As I had many issues with it. It is very sensitive to tilting. E.g. if the expansion card is not parallel to the main board. Next, I would check clock and address signals are coming to the CPLD. Also the CPLD has a couple of test signals on "Test" connector as below, so you can check if address decoder works:
assign TEST[0] = Z2_ADDRESS; //p100 - Zorro2 address access
assign TEST[1] = Z2_nWRITE; // p99 - Zorro2 write 
assign TEST[2] = Z2_nREAD;  // p98  - Zorro2 read
assign TEST[3] = configured;// p97  - Kickstart configured the RAM
assign TEST[4] = debug_bit;  - set if shutup command received
assign TEST[5] = FR_RESET; - delayed RESET
assign TEST[6] = POR[2]; - Reset counter (used for the above delay)
assign TEST[7] = (A[23:16] == 8'hE8); - access to address space 0xE80000

I did not try to start the card without RAM chips, so can not say how it behave.

**Comment by Retrofletch** [comment]
Connector seems fine no pins seems off, i even touched up all sodlering points but no change.
i have another 8mb card ( the one based on tf328 ) uses same connector i plug that in and no issue with that.

14mhz clock does make it to the cpld, there are some activity on adress ( measured on cpld) for a second or so then it all shuts down, some of the test points goes high ( it seems ) but not sure what to make of it..

i feel like something is up with the cpld, can you confirm that the file i programmed is correct and works for you?
i will build another one when i get more a1200 connectors next week and see if second card acts the same.. its verry odd =/
Was hoping i could get this one working as the xilinx parts for the edu arana one is getting hard to buy and the added RTC is nice bonus.

anyways thanks for responding.

**Comment by OlegMishin** [comment]
The main difference to the board I built is the CPLD. I used ATF1508 as EPM is not in production any more. Answering your question, I have never tested the design with Altera CPLD. But for the ATF I used the same "pld_ram.pof" file which was converted to .jed and then to .svf for flashing.
Would be helpful to get the EPM CPLD in my hands. Let see if I can order it somewhere.

**Comment by Retrofletch** [comment]
I will build another one next week, if it acts same way I can just send you the card along with a couple epm's if you wish, unfortunatly troubleshooting this is a bit out of my league

**Comment by OlegMishin** [comment]
Sounds good for me if it is ok for you to ship to Germany. It would be nice to check the design with EPM. 
Just couple of thoughts. 
First, I hope you got the EPM's from a trusted seller(like Digikey or similar). I have some bad experience buying CPLDs from China :) 
And second, I tested my card with the latest ReAmiga only. If you have some other revision mainboard it might be needed to apply "Timing Fix" like discussed here:
https://retrocomputing.stackexchange.com/questions/609/what-are-the-amiga-1200-timing-fixes

**Comment by bfgmatik** [comment]
Just wanted to advise that Retrofletch's problems may be caused by the same reason as mine (D16 and D17 short by 5V via). After fix my card works properly. Thanks for a good work!

**Comment by OlegMishin** [comment]
@bfgmatik thank you for the finding. And my apologies for the stupid mistake. Normally I do DRC every time when change something. Seems in this case I forgot to do that. As this revision was never produced(I still use my pilot board), the problem was not discovered. 
Anyway, thanks again. The gerber files have been updated.

Regards
Oleg

**Comment by Retrofletch** [comment]
Hello
@bfgmatik and @OlegMishin 
I acctually put this whole thing on ice as i ordered new ram chips, i suspected i had used the wrong kind ( FPM vs edo ) and never got around to testing any more.

I just checked D16 and D17 and sure enough, they are both shorted to 5v, as there are no kicad files available im struggling to find best place to resolve this issue, how did you bodge it on your card bfgmatik?

thank you for taking the time to troubleshoot this issue, it was beyond my own capability unfortunatly.

and Oleg, no need to apogogise these things happen and i took a calculated risk ordering untested board, im happy people bother putting their stuff on github in the first place!

**Comment by Retrofletch** [comment]
Also a bit unrelated to the boot issue, but mentioned was that the rev0 did not fit well and had to be filed down, i have same issue still on the rev1 board, i had to file it down on the side next to the battery holder to make it fit, it seems there are no tracks there so i think the pcb could be adjusted quite easily to make it a better fit. did you experience this also @bfgmatik ?

**Comment by bfgmatik** [comment]
The solution was to cut these two traces which are shorted a little further by 5V via. Of course it will make RTC not working and need to be rewired to proper RTC pins (after another cut after the via to remove short circuit on RTC side). I'm going to do it on Monday in my workshop. But for now it works correctly without RTC.
![A1200_fastram_bug](https://user-images.githubusercontent.com/126353266/221379068-5abd668c-69c2-4cd2-bc02-26b9366a37e7.JPG)
My board fits quite well into A1200, it could be around 0.5mm shorter on one side for better fitting. Also my RTC battery connector collides a little with bottom cap and should be moved at at least few milimeters in RTC direction. I had to use knife on bottom cap to make it compatible :).

**Comment by bfgmatik** [comment]
I wonder how many people "borrowed" Oleg's design and started to sell it with this bug :). I bought my on Polish auction webpage. :D.

**Comment by Retrofletch** [comment]
i will try this fix, thank you

well i know of atleast one guy on polish allegro who is well known for doing just that, and even sell things that say on pcb not to sell he just puts a sticker over it :) could not find this board in his items tho so maybe they have multiplied :p

**Comment by bfgmatik** [comment]
He doesn't sell it because I bought his last one :). Well, a good thing about that was that this PCB was quite heap compared to ordering 1 piece of 4-layer PCB even from China.
Some more pictures about my board dimension problems.
![A1200_fastram_02](https://user-images.githubusercontent.com/126353266/221379813-36087dbc-56eb-4d27-a00a-e6d1bce54abe.JPG)
![A1200_fastram_03](https://user-images.githubusercontent.com/126353266/221379819-2b7b11ad-4dfd-413d-8c67-a739aa1c003e.JPG)

**Comment by Retrofletch** [comment]
Yes that on the second image is exactly where my board is hitting aswell, i think remove even 1-2mm there would help, my board sits at a slight angle on the edge connector as it is wich worry me a bit. there is no traces there so should be no issue.

and also, good news, i cut the two traces on my board, now it boots fine and 8mb shows up in ATK, seems this was only issue! amazing!

**Comment by OlegMishin** [comment]
Thanks for your feedback, guys. I can update the board outline as well. 
Did I get correctly, it should be modified like below, right?
![image](https://user-images.githubusercontent.com/81614352/221380263-4b332df1-3611-4700-a4da-6b394d7c15a3.png)

**Comment by Retrofletch** [comment]
That would be perfect yes!
and i guess if i understand bfg correctly it would also be good to move battery holder inwards toward rtc chip a bit if at all possible

**Comment by bfgmatik** [comment]
In my opinion also CR2032 should be moved at least 5mm left (towards RTC) to fit with my battery holder and bottom cap/cover. Maybe my holder is taller or wider than your but all of them are quite similar.

**Comment by bfgmatik** [comment]
OK, this may be only the matter of my battery holder, because it goes out of the silkscreen line so I assume that yours have a little different dimensions.

**Comment by Retrofletch** [comment]
i cut the traces both sides of the via and linked up again with some enamel wire and poured some solder mask over it to secure it all, RTC works as it should aswell now.
so with these small fixes to the board i think we got a winner :)

**Comment by OlegMishin** [comment]
@Retrofletch good to read that. Checking again the board with my Amiga, I found that the battery holder indeed is to close to board edge and I did cut some plastic of Amiga's case. Already forgot about that :)
I've fixed the board and uploaded schematic/gerbers as Rev 2.
