### ISSUE TITLE
D16, D17 and 5V short-cicuit by 5V via? 

### ISSUE THREAD

**Issue by bfgmatik** [OlegMishin/A1200_8MB_FASTRAM#3]
Well, looks like there is a mistake on the PCB near R3 which causes a short circuit between D16, D17 and 5V. Can you confirm this? :)

**Comment by OlegMishin** [comment]
You are right. Shame on me....
The board needs some surgery here(top view):
![image](https://user-images.githubusercontent.com/81614352/221376094-595d113f-1b36-41da-8dd6-2a67b2f6a8f6.png)
I will update the gerbers in short.

**Comment by OlegMishin** [comment]
Gerbers have been updated.
