### ISSUE TITLE
Production files and JLC

### ISSUE THREAD

**Issue by Retrofletch** [OlegMishin/A1200_8MB_FASTRAM#4]
It seems with new December 2022 rules JLC will no longer accept the gerbers, I tried order the new revision

Their response is as follows: " As shown below, we have new rule since Dec, 2022, if the copper areas are less than 30% of the board in each copper layer, the space between trace and trace should be at least 0.15mm to avoid short circuit. The space in your file is not enough.

There are two option to deal with this case

A customer enlarge the space between trace and trace at least 0.15mm

B customer add more copper area to reach at least 30% of the inner layer. For the extra copper, if the copper surface are not a part of circuit net, we call false copper, please make sure the space between copper to the trace, pad, hole and real copper surface at least 1.0mm.
"

So I'm guessing adding some copper fill would resolve thus quite easy without having to mess with traces spacing.

They also said there is no defined keepout area but that is less of an issue as they can just use the outer frame of a layer. 

I'd do it myself but only gerbers are available :)

**Comment by OlegMishin** [comment]
Hi @Retrofletch,
Thanks for your feedback! I have updated the gerbers with the following:
1. increased clearance to 0.15 mm. 
2. filled TOP/BOT layers with GND poly
Now it should fit JLC rules. 

I would prefer not share the sources in public. Anyway, the project is in Altium Designer, might be not so much useful. If you need I can share the sources via email.

**Comment by Retrofletch** [comment]
That seems to have fixed the issues, they accepted the gerbers now thanks

i know other people have had designs that passed on JLC previously without problem are now getting rejected and needed changes, mostly because the lack of copperfills.

No i understand not everyone want 20 slightly different versions of their designs out there that people are asking for support on, and i also do not know how to use altium so that probably would not have helped anyways :) 

Think the board is all good now anyways, thanks for quick reply :)

**Comment by OlegMishin** [comment]
No problem. Enjoy the building :)
